### ISSUE TITLE
Outdated storagenode binaries cause node to fail to start

### ISSUE THREAD

**Issue by nkbphazon** [utropicmedia/storj-freenas#2]
This plugin ships with storagenode version 1.6.3, which is below the minimum required version to run:

`
2020-09-11T11:46:07.579-0500 WARN version version not allowed/outdated {"current version": "1.6.3", "minimum allowed version": "v1.9.0"}
Error: outdated software version (v1.6.3), please update
`

The post_install script is hard-coded to version 1.6.3
https://github.com/storj-thirdparty/freenas-storagenode-app/blob/f1c0dd0d7d56c0d1af8020bec980c57e2565bf5d/post_install.sh#L79

https://github.com/storj-thirdparty/freenas-storagenode-app/blob/f1c0dd0d7d56c0d1af8020bec980c57e2565bf5d/post_install.sh#L73

The "update" script is hard-coded to version 1.6.3 just re-downloads the same binary that is already installed.
https://github.com/storj-thirdparty/freenas-storagenode-app/blob/f1c0dd0d7d56c0d1af8020bec980c57e2565bf5d/overlay/usr/local/www/storagenode/scripts/storagenodeupdate.sh#L15

I suggest updating these URLs to use the most recent release from the storj repo instead of hard-coding specific versions:

https://github.com/storj/storj/releases/latest/download/storagenode_freebsd_amd64.zip
https://github.com/storj/storj/releases/latest/download/identity_freebsd_amd64.zip

**Comment by kmozurkewich** [comment]
Hi @nkbphazon - any updates for this repo are going into a backlog for now, however, if you want to cut a PR we'd be happy to review and merge.

**Comment by nkbphazon** [comment]
I locally updated the code and deployed it but ran into several other issues. I don't have the time to continue pursuing the plugin approach and opted to stand up a VM running docker instead.
